In [ ]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.shape
x.ndim


[[1 2 3]
 [4 5 6]]


2

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.dtype
x.astype(np.float16)

[[1 2 3]
 [4 5 6]]


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.size

[[1 2 3]
 [4 5 6]]


6

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
x.itemsize

[[1 2 3]
 [4 5 6]]


8

In [ ]:
import numpy as np

ar4 = ([1,2,3,4,5,6])
print(ar4)

ar4 = np.array([1,2,3,4,5,6])
print(ar4)

ar4

ar4.dtype

ar4.ndim

ar4.size

ar4.itemsize

ar4.nbytes

ar4.reshape(2,3)

ar4.reshape(3,2)

ar4.ravel()

ar4.min()

ar4.max()

ar4.sum()

ar4.sum(axis=0)

ar4.transpose()

ar5 = np.array([[1,2,3],[4,5,6],[7,8,9]])
ar5

ar5 = np.arange(1,10).reshape(3,3)
ar5

ar6 = np.array([[11,12,13],[14,15,16],[17,18,19]])
ar6

ar6 = np.arange(11,20).reshape(3,3)
ar6

ar5 + ar6

ar5.transpose()

ar5.dot(ar6)

np.hstack((ar5,ar6))

np.vstack((ar5,ar6))

np.split(ar5,3)

np.hsplit(ar5,3)

np.vsplit(ar5,3)

ar1=np.arange(11,47).reshape(6,6)
ar1

ar1[1:6,1:4]

ar1[:5,:5]

ar1[2:6][2:4]

ar1

ar1[3::1,0::6]



ar1[0:2,2:]

ar1[5:,3]

arr2=np.arange(24).reshape(6,4)
arr2


arr2[2:4,1:3]

arr2[4:,2:]

arr2[3:5,0:2]

arr2

arr2[2:4,2:]

arr2[2,1:3]

a2 = np.arange(12).reshape(3,4)
a2



a3 = np.arange(8).reshape(2,2,2)
a3

a2

a2[2,1]

a2[1,2]

a2[2,3]

a2[1,0]

a2[0,3]

a2[1:4,2:3]

a2

a2[2:,2:]

a2[1:2,1:3]

a2[2:3,1:3]

a2[1:2,0:2]

a2


a2[1:2,2:4]

a2[0:3,2:3]

a3

a3[1,0,1]

a3[0,1,1]

a3[0,0,0]

a3[1,1,0]

a2

a2[0,:]

a2[:,2]

a2[1:,1:3]

a2

a2[::2,::3]

a2[::2,1::2]

a2[::2,1:3]

a = np.arange(24).reshape(4,6)
a

a[[0,2]]  # famcy indexing



a[[2,3]]

a[:,[2,4]]

a[:,[0,2,4]]

import numpy as np
a = np.random.randint(1,100,24).reshape(4,6)
a

a > 50

a[a>50]

a % 2 == 0


a[a%2==0]  # flitring the boolean indexing

import matplotlib.pyplot as plt

x = np.linspace(-5,10,5)
y = np.sin(x)
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = x
plt.plot(x,y)


import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = x**2
plt.plot(x,y)


x = np.linspace(-10,10,100)
y = np.sin(x)
plt.plot(x,y)



x = np.linspace(-10,10,100)
y = x*np.log(x)
plt.plot(x,y)



